import type { Metadata } from "next";
import { Varela_Round } from "next/font/google";
import "./globals.css";
import Sidebar from "./sidebar";

const varela_round = Varela_Round({
  variable: "--font-varela-round",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${varela_round.variable} ${varela_round.variable} antialiased overflow-hidden flex flex-row flex-nowrap w-screen h-screen`}
      >
        <Sidebar />
        <div className={`h-full w-5/6 overflow-y-scroll p-6 pl-16`}>
          {children}
        </div>
      </body>
    </html>
  );
}
